name: "Terraform CI/CD pipeline"

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: 
  contents: read

jobs:
  terraform:
    name: "Terraform Automation"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0"

      - name: Configure AWS Credentials
        uses: aws_actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:
